apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-python
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alves0611/ci-cd-gitops
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
