resources:
- backend/deployment.yml
- backend/service.yml

images:
- name: 165304687371.dkr.ecr.us-east-1.amazonaws.com/studying/dev/backend
  newName: 165304687371.dkr.ecr.us-east-1.amazonaws.com/studying/dev/backend
  newTag: e8a7276097f513e4b82143a5fadd350f4bcbffb2
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
